### PR TITLE
Allow omnifaces.ui and omnifaces.functions URN namespaces

### PR DESCRIPTION
**Pull request by melloware**
I know you did this for 5.0 but in 4.0 and 4.1 people are already used to URN's and we did the same thing for PrimeFaces so people can use either `primefaces` or `https://www.primefaces.org/primefaces` using URL or URN with this.

### CODE REVIEW

**Comment by BalusC** [comment]
Much appreciated but personally I'm still hesitating whether to simply merge them into xmlns:o="omnifaces" and I wanted to let sink this in good before introducing a breaking change. Or perhaps I could even add (xsl-generate obv) that on top of these two?

WDYT?

**Comment by melloware** [comment]
Either is fine for me I have tested with PrimeFaces with this same fix and since its two distinct `taglib.xml` all IDES and builds pick it up fine so either `xmlns:o="omnifaces.ui"` works or the legacy `xmlns:o="http://omnifaces.org/ui"` still works and people can transition when they want.

**Comment by BalusC** [comment]
I mean, I was playing with the idea to merge `xmlns:o="omnifaces.ui"` and `xmlns:of="omnifaces.functions"` into a single `xmlns:o="omnifaces"`, or to simply add it on top of these two.

**Comment by melloware** [comment]
OHHH i like that even better.

**Comment by BalusC** [comment]
I decided to merge them into a single taglib with `xmlns:o="omnifaces"`: https://github.com/omnifaces/omnifaces/commit/ea65a969d3d4cdf2977adf4b001c0c1078c7b092

So this basically invalidates the current PR I think. Unless I decide to add another xsls to generate the necessary taglib.xml files for xmlns:o="omnifaces.ui" and xmlns:of="omnifaces.functions" as well. But I'm not sure having that many namespaces is convenient/clear for the end users. PrimeFaces also has all its tags and functions in a single namespace for ages and no one really complained.

**Comment by melloware** [comment]
Thanks I will close!

**Comment by melloware** [comment]
Were you going to backport to 4.x?

**Comment by BalusC** [comment]
Yeah I probably should. Will take a look other day.

**Comment by BalusC** [comment]
https://github.com/omnifaces/omnifaces/issues/877

**Pull request closed without merging**
