### PR TITLE
PWA WebAppManifest orientation default null

### PR DESCRIPTION
**Pull request by pizzi80**

### CODE REVIEW

**Comment by pizzi80** [comment]
I was struggling with the tests... I don't know why there were different results between local and github...

**Comment by BalusC** [comment]
LGTM and merged. But,

> I was struggling with the tests... I don't know why there were different results between local and github...

Can you please elaborate the difference at local?

**Comment by pizzi80** [comment]
### Regarding the test PWAResourceHandlerIT

I updated the branch with the other PWA PR (Screenshot + Shorcut)   
But during the PWAResourceHandlerIT run, the produced webapp manifest 
was still without the `\"screenshots\":[],\"shortcuts\":[],` part  

So, after some testing, I made the change and moved it to a new branch/PR
and on github the test passed

### Other Tests

  On my pc there are some failing tests which a I have now locally
  disabled/fixed, but I'm not sure that the fix is right for everyone... 
  I'm not very experienced in this area

 - TestUtils is failing the check of serializeURLSafe against the "precomputed" values
 
 - ViewResourceHandlerIT has a problem of "timezone" on my pc, 
   I was unable to align the generated sitemap lastmod timezone 
   with the timezone inside the statically generated string "EXPECTED_XML_BODY"
   
 - ParamIT test has problem with the default locale ... 
 
 
 If you want I can try to make PR with some changes

**Comment by BalusC** [comment]
Ok, I will look closer later. Full test error reports will definitely be helpful.

To be clear:
- to run unit tests only (all `TestXyz` classes), do `mvn clean test`
- to run a specific unit test (e.g. `TestFoo` class), do `mvc clean test -Dtest=TestFoo`
- to run IT tests as well (all `XyzIT` classes), do `mvn clean verify`
- to run a specific IT test (e.g. `FooIT` class), do `mvn clean verify -Dit.test=FooIT`
- to run IT tests on a specific server (e.g. Tomcat MyFaces 4), do `mvn clean verify -P tomcat-myfaces4` where the `tomcat-myfaces4` part matches the desired `<profile><id>` declared in `pom.xml`

As to your `PWAResourceHandlerIT` failure, most probably OmniFaces JAR wasn't correctly cleaned/rebuilt after merge. Using `clean` in the `mvn` command guarantees a fresh OmniFaces JAR.

**Comment by pizzi80** [comment]
thanks for the manual!!! :smiley: :top:

**Pull request merged**
