### PR TITLE
Hacks: Check and restore original MyFaces value

### PR DESCRIPTION
**Pull request by melloware**
@BalusC while reviewing this code i thought this seemed odd it was setting it always back to FALSE overriding the users web.xml value?  Shouldn't this restore the original MyFaces value and only go back to FALSE if not set?

### CODE REVIEW

**Comment by melloware** [comment]
Actually I am pretty sure this hack is no longer needed.

**Comment by BalusC** [comment]
According to commit history it was added to fix https://github.com/omnifaces/omnifaces/issues/361 so we need to reasses this (and I want to add an integration test for that too because I currently don't anymore clearly remember/understand how exactly to reproduce this).

**Comment by BalusC** [comment]
Ok finally boiled down the reproducer after digging in old emails where issue 361 was linked.

MyFaces 2.2.12 was used and the page had a `<f:viewAction action>` referring a `@ViewScoped` bean method. The scripts were correctly generated but the view state couldn't be found/destroyed during unload request (for a yet unclear reason but it was definitely related to OmniFaces.unload.init script component missing the id). I reproduced it in a sandbox project. Outcommenting the Hacks.setComponentResourceUniqueId() indeed demonstrated the problem in a modified 2.7.27 version. To be exact, the `viewRootState = ((Map) componentState).get(view.getClientId(context));` line of OmniViewHandler unexpectedly returned null. I'll have to bake an IT based on it and test newer MyFaces versions.

**Comment by BalusC** [comment]
Added the IT to 3.x. It's still reproducible in MyFaces 2.3.10. That is, the IT fails when I outcomment the Hacks.setComponentResourceUniqueId(). So it is definitely still needed.

**Comment by BalusC** [comment]
Also still reproduced with MyFaces 4.0.2 when I outcomment Hacks.setComponentResourceUniqueId() in ComponentsLocal of OmniFaces 4.x.

**Comment by BalusC** [comment]
As to the current PR,

> @BalusC while reviewing this code i thought this seemed odd it was setting it always back to FALSE overriding the users web.xml value? Shouldn't this restore the original MyFaces value and only go back to FALSE if not set?

It's not some user web.xml config. It's just a flag whether to generate a component ID following MyFaces-internal rules for component resources. MyFaces itself does exactly the same thing in [ApplicationImpl](https://github.com/apache/myfaces/blob/myfaces-core-module-4.0.2/impl/src/main/java/org/apache/myfaces/application/ApplicationImpl.java#L1748-L1758). So I don't think this PR fixes anything.

Just to be clear I haven't yet analyzed why exactly MyFaces does this and why exactly the OmniFaces @ViewScoped unload view state destroy fails when this is removed.

**Comment by melloware** [comment]
OK i will close!

**Pull request closed without merging**
