### PR TITLE
Components & ComponentsLocal

### PR DESCRIPTION
**Pull request by pizzi80**
https://github.com/omnifaces/omnifaces/issues/848

Not a simple task ... 😵‍💫
I tried to follow your code style for splitted classes' version
like `Ajax` and `AjaxLocal`

Let me know if I have to change something!

### CODE REVIEW

**Comment by BalusC** [comment]
Tests are failing due to compilation errors.

And, in the javadocs of `XyzLocal` you can use `@see` to refer same javadoc in `Xyz` without the need to copy paste it.

And, `@since` on method is unnecessary if class has already same `@since`.

**Comment by pizzi80** [comment]
> Tests are failing due to compilation errors.
> And, in the javadocs of XyzLocal you can use `@see` to refer same javadoc in Xyz without the need to copy paste it.
> And, `@since` on method is unnecessary if class has already same `@since`.

Ok!!!



**Question**: To simulate the same check of github, do I have to run `mvn verify` ?

**Question 2:** 
Is there a way to force Faces to run in english during tests? 
on my IDE they runs in italian :) and some test fails because of that, for example 

```
[ERROR] org.omnifaces.test.cdi.param.ParamIT.testInvalidStringParam -- Time elapsed: 0.165 s <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <size must be between 2 and 2147483647> but was: <la dimensione deve essere compresa tra 2 e 2147483647>
```

this fails only because Faces is running in italian 
and the validation message bundle it's obviously different ...

**Comment by BalusC** [comment]
> **Question**: To simulate the same check of github, do I have to run `mvn verify` ?

Yes, `mvn verify` runs surefire (unit tests) and failsafe (integration tests) whereas `mvn test` only runs surefire.

> **Question 2:** Is there a way to force Faces to run in english during tests? on my IDE they runs in italian :) and some test fails because of that, for example

Oh right. I've just [fixed](https://github.com/omnifaces/omnifaces/commit/5c291054c921744deb2bf3ff94e7e580b32b71a2) that, please retry.

**Comment by pizzi80** [comment]
Thanks for all the info as usual !!

I've fixed the documentation e improved the split 

let me know 


> Oh right. I've just [fixed](https://github.com/omnifaces/omnifaces/commit/5c291054c921744deb2bf3ff94e7e580b32b71a2) that, please retry.

didn't fix the language 

If I set the default language in the various faces.config.xml it works

I will do a separate PR so you can evaluate better

**Comment by BalusC** [comment]
> didn't fix the language
> 
> If I set the default language in the various faces.config.xml it works

Hmm ok. Shouldn't be necessary. I will take a second look later.

**Comment by BalusC** [comment]
Ok I reverted my change and merged your PR with faces config default locale.

**Pull request merged**
