### PR TITLE
Fix #556: Look for Quarkus /META-INF/web.xml

### LINKED ISSUE #556: Quarkus web.xml location
It looks like some Quarkus apps use /META-INF/web.xml a location for web.xml.

See:  https://github.com/quarkusio/quarkus/issues/3457

So I think this location should be added to web.xml parser similar to PrimeFaces: https://github.com/primefaces/primefaces/issues/5968

### PR DESCRIPTION
**Pull request by melloware**

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @melloware, I've tested your change on [this quarkus-omnifaces](https://github.com/rmpestano/quarkus-omnifaces/tree/master/system-tests) sample project.

I've added a web.xml in META-INF folder and configured [number of views in session](https://github.com/rmpestano/quarkus-omnifaces/blob/9818d96b7457e75f9b056b925d2623c48dec3090/system-tests/src/main/resources/META-INF/web.xml#L8-L18).

But I got same behaviour with OmniFaces 3.4.1 and the version from your branch. 
In both cases the number of active view scoped beans are being configured properly the only strange thing (in both cases) is that after the number of active beans is reached none of the views (tabs in browser) work anymore and in the logs I got the following:

```
[INFO] ------------------------------------------------------------------------
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
Using OmniFaces version 3.4
Using org.apache.myfaces.webapp.MyFacesContainerInitializer
MyFaces Core Bean Validation support disabled
MyFaces Core CDI support enabled
MyFaces Core EL 3.0 support enabled
MyFaces Core Servlet 4.0 support enabled
Running on PrimeFaces 8.0


********************************************************************
*** WARNING: Apache MyFaces Core is running in DEVELOPMENT mode. ***
***                                            ^^^^^^^^^^^       ***
*** Do NOT deploy to your live server(s) without changing this.  ***
*** See Application#getProjectStage() for more information.      ***
********************************************************************


MyFaces Core has started, it took [429] ms.
quarkus-omnifaces-st 1.5.0.Final on JVM (powered by Quarkus 1.5.0.Final) started in 1.600s. Listening on: http://0.0.0.0:8080
Profile prod activated. 
Installed features: [cdi, myfaces, omnifaces, servlet]
org.apache.myfaces.view.facelets.el.ContextAwarePropertyNotFoundException: javax.el.PropertyNotFoundException: Target Unreachable, [sampleBean] returned null
        at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getType(ContextAwareTagValueExpression.java:87)
        at org.apache.myfaces.renderkit.RendererUtils.findUIOutputConverter(RendererUtils.java:401)
        at org.apache.myfaces.renderkit.RendererUtils.getConvertedUIOutputValue(RendererUtils.java:796)
        at org.apache.myfaces.renderkit.html.base.HtmlTextRendererBase.getConvertedValue(HtmlTextRendererBase.java:356)
        at javax.faces.component.UIInput.getConvertedValue(UIInput.java:772)
        at javax.faces.component.UIInput.validate(UIInput.java:691)
        at javax.faces.component.UIInput.processValidators(UIInput.java:302)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1406)
        at javax.faces.component.UIForm.processValidators(UIForm.java:204)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1406)
        at javax.faces.component.UIComponentBase.processValidators(UIComponentBase.java:1406)
        at javax.faces.component.UIViewRoot._processValidatorsDefault(UIViewRoot.java:1761)
        at javax.faces.component.UIViewRoot.access$500(UIViewRoot.java:83)
        at javax.faces.component.UIViewRoot$ProcessValidatorPhaseProcessor.process(UIViewRoot.java:1869)
        at javax.faces.component.UIViewRoot._process(UIViewRoot.java:1717)
        at javax.faces.component.UIViewRoot.processValidators(UIViewRoot.java:967)
        at org.apache.myfaces.lifecycle.ProcessValidationsExecutor.execute(ProcessValidationsExecutor.java:39)
        at org.apache.myfaces.lifecycle.LifecycleImpl.executePhase(LifecycleImpl.java:172)
        at org.apache.myfaces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:125)
        at javax.faces.webapp.FacesServlet.service(FacesServlet.java:207)
        at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
        at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:63)
        at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
        at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
        at io.undertow.servlet.handlers.RedirectDirHandler.handleRequest(RedirectDirHandler.java:67)
        at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:133)
        at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
        at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:65)
        at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
        at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
        at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
        at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:247)
        at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:56)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:111)
        at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:108)
        at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
        at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$10$1$1.call(UndertowDeploymentRecorder.java:563)
        at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:227)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:152)
        at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:113)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$6$1.run(UndertowDeploymentRecorder.java:396)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.el.PropertyNotFoundException: Target Unreachable, [sampleBean] returned null
        at org.apache.el.parser.AstValue.getTarget(AstValue.java:124)
        at org.apache.el.parser.AstValue.getType(AstValue.java:58)
        at org.apache.el.ValueExpressionImpl.getType(ValueExpressionImpl.java:174)
        at org.apache.myfaces.view.facelets.el.ContextAwareTagValueExpression.getType(ContextAwareTagValueExpression.java:83)
        ... 59 more

``` 

To reproduce, just open 4 tabs in browser using this URL: `http://localhost:8080/index.xhtml?id=1`

Go to first opened tab and try to save the form.

**Comment by rmpestano** [comment]
By the way, you need to [change here](https://github.com/rmpestano/quarkus-omnifaces/blob/9818d96b7457e75f9b056b925d2623c48dec3090/runtime/pom.xml#L46) to use your omnifaces version

**Comment by melloware** [comment]
@rmpestano I think it only fixes WebXml class of OmniFces so for example if in your web.xml you had..
```xml
	<session-config>
		<session-timeout>480</session-timeout>
		<cookie-config>
			<http-only>true</http-only>
		</cookie-config>
		<tracking-mode>COOKIE</tracking-mode>
	</session-config>
```

In OmniFaces if you then asked for...
```java
int sessionTimeout = WebXml.instance().getSessionTimeout();
```

it should find your META-INF/web.xml and report 480.  Can you try that?

**Comment by rmpestano** [comment]
I'm getting `-1`:
Screenshot 2020-06-02 at 14 15 45 1

I've just updated omnifaces quarkus sample app to use session timeout so you can try there

**Comment by melloware** [comment]
thanks let me test.

**Comment by melloware** [comment]
@rmpestano reported this issue as I can't get your project to build: https://github.com/rmpestano/quarkus-omnifaces/issues/4

**Comment by rmpestano** [comment]
Hi @melloware, just tested and now it is working great!

 
Screenshot 2020-06-03 at 08 58 23 1

**Comment by melloware** [comment]
@rmpestano thank you so much for testing and verifying!

**Pull request merged**
