### PR TITLE
Make Lazy class serializable - 4.x

### LINKED ISSUE #731: Make Lazy serializable
Self-explanatory, PR submitted
Major use case is to be able to use inside `@ViewScoped` and `@SessionScoped` beans with ease

### PR DESCRIPTION
**Pull request by lprimak**
fixes #731

### CODE REVIEW

**Comment by melloware** [comment]
@BalusC told me we only need to submit PR for the "lowest" level and then he promotes it up so you can close this one and leave your 3.x one open!

**Comment by lprimak** [comment]
But I already cherry picked it :) Less work for @BalusC :)

**Comment by melloware** [comment]
Good stuff

**Comment by BalusC** [comment]
3.x has been merged into 4.x via https://github.com/omnifaces/omnifaces/commit/b7236ec6f95bc9ad33b4b9d2198bedb9624640e4

**Pull request closed without merging**
